### PR TITLE
Use Composer-style constrain

### PR DESCRIPTION
**Pull request by szepeviktor**
kép

### CODE REVIEW

**Comment by g105b** [comment]
Hi @szepeviktor ,

Thank you for this. It took me a while to understand the difference, but I agree that using the Caret Version Range is beneficial for this Action, because of the lack of major stable release at phpstan. ^0.12.26 will upgrade to 0.13.0 but 0.12.* will not.

Thanks, I'll test this on a repository and merge your change in soon.

**Comment by szepeviktor** [comment]
> because of the lack of major stable release at phpstan. ^0.12.26 will upgrade to 0.13.0 but 0.12.* will not.

Please see https://jubianchi.github.io/semver-check/#/^0.12.0/0.13.1

**Comment by szepeviktor** [comment]
Docs: https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by g105b** [comment]
Thanks for the info. Great to have you on board!

**Pull request merged**
